Add namespace as target for @access decorator
Azure/typespec-azure pull request #1305
Opened 2024-08-06 20:51 UTC by joheredi

Fixes [#1301](https://github.com/Azure/typespec-azure/issues/1301)

2024-08-06 20:54 UTC, azure-sdk commented
<!--chronus-github-change-commenter-->
:x: There is undocummented changes. Run `chronus add` to add a changeset or [click here](https://github.com/joheredi/typespec-azure/new/add-access-to-namespace?filename=.chronus/changes/add-access-to-namespace-2024-7-6-20-54-22.md&value=---%0A%23%20Change%20versionKind%20to%20one%20of%3A%20internal%2C%20fix%2C%20dependencies%2C%20feature%2C%20deprecation%2C%20breaking%0AchangeKind%3A%20fix%0Apackages%3A%0A%20%20-%20%22%40azure-tools%2Ftypespec-client-generator-core%22%0A---%0A%0AAdd%20namespace%20as%20target%20for%20%40access%20decorator).

**The following packages have changes but are not documented.**
 - :x:`@azure-tools/typespec-client-generator-core`

<details>
<summary>Show changes</summary>


</details>

2024-08-06 22:06 UTC, iscai-msft approved these changes

2024-08-07 03:37 UTC, tadelesh requested changes

2024-08-07 03:37 UTC, tadelesh commented on packages/typespec-client-generator-core/lib/decorators.tsp
> + * if the model has an access override, the model override takes precedence.
```suggestion
 * the access info will be propagated to the models defined in the namespace.
 * If the model has an access override, the model override takes precedence.
```

2024-08-07 03:37 UTC, tadelesh commented on packages/typespec-client-generator-core/src/decorators.ts
> +) {
this func is used for get final calculation result of access, so i don't think we should add namespace

2024-08-07 03:37 UTC, tadelesh commented on packages/typespec-client-generator-core/src/decorators.ts
>    const override = getScopedDecoratorData(context, accessKey, entity);
```suggestion
  const override = getAccessOverride(context, entity);
```

2024-08-07 03:37 UTC, tadelesh commented on packages/typespec-client-generator-core/src/decorators.ts
>      return override || "public";
```suggestion
    return override;
```

2024-08-07 03:37 UTC, tadelesh commented on packages/typespec-client-generator-core/src/decorators.ts
> +    case "Namespace":
```suggestion
    case "Operation":
```

2024-08-07 03:37 UTC, tadelesh commented on packages/typespec-client-generator-core/test/decorators.test.ts
> +    })
also need test for operation

2024-08-08 00:03 UTC, azure-sdk commented
<!-- _TSP_TRYIT_COMMENT_ -->
You can try these changes here

| [🛝 Playground]( https://cadlplayground.z22.web.core.windows.net/typespec-azure/prs/1305/)|[🌐 Website](https://tspwebsitepr.z22.web.core.windows.net/typespec-azure/prs/1305/)|[📚 Next docs](https://tspwebsitepr.z22.web.core.windows.net/typespec-azure/prs/1305/docs/next.html) |
| ---|---|--- |

2024-08-08 02:26 UTC, tadelesh approved these changes

2024-08-08 21:01 UTC, joheredi commented on packages/typespec-client-generator-core/test/decorators.test.ts
> +    })
Added additional tests

2024-08-08 21:29 UTC, merged