Default Experiences
Azure/typespec-azure pull request #1536
Opened 2024-09-13 19:51 UTC by cameronking4

Generating Azure Portal default experiences using Typespec, link to latest documentation. 

Using link rather than copying over content for easier maintenance.

2024-09-19 17:07 UTC, timotheeguerin commented
/azp run typespec-azure pr-tools

2024-09-19 17:08 UTC, timotheeguerin commented
/azp run typespec-azure pr tools

2024-09-19 17:14 UTC, timotheeguerin commented
/azp run typespec-azure - PR Tools

2024-09-19 17:16 UTC, azure-sdk commented
<!--chronus-github-change-commenter-->
No changes needing a change description found.

2024-09-19 17:34 UTC, azure-sdk commented
<!-- _TSP_TRYIT_COMMENT_ -->
You can try these changes here

| [🛝 Playground]( https://cadlplayground.z22.web.core.windows.net/typespec-azure/prs/1536/)|[🌐 Website](https://tspwebsitepr.z22.web.core.windows.net/typespec-azure/prs/1536/)|[📚 Next docs](https://tspwebsitepr.z22.web.core.windows.net/typespec-azure/prs/1536/docs/next.html) |
| ---|---|--- |

2024-09-27 00:02 UTC, cameronking4 commented on docs/howtos/Azure Portal/default-experiences.md
> +Go to the [TypeSpec guide](https://typespec.io/docs/next/libraries/http/content-types#content-type-negotiation) to learn how to customize a default Azure Portal experience for your resource types usi
Fixed thanks.

2024-09-27 00:03 UTC, cameronking4 commented
/azp run typespec-azure - PR Tools

2024-09-27 20:45 UTC, yejee94 approved these changes

2024-09-27 20:46 UTC, yejee94 commented on docs/howtos/Azure Portal/default-experiences.md
> +Go to the [TypeSpec guide](https://eng.ms/docs/products/azure-portal-framework-ibizafx/declarative/typespec) to learn how to customize your Azure Portal experience, generated by default for your ARM
nit: bit confusing for me :)

2024-10-30 19:52 UTC, markcowl approved these changes

2024-10-30 19:53 UTC, markcowl requested changes
Need to run `pnpm format` to clear the formatting issue

2024-12-06 00:25 UTC, markcowl commented
closing in favor off: https://github.com/Azure/typespec-azure/pull/1953

2024-12-06 00:25 UTC, closed without merging