[tcgc] support value type for client default value
Azure/typespec-azure pull request #1631
Opened 2024-09-30 09:31 UTC by tadelesh

fix: https://github.com/Azure/typespec-azure/issues/1598

2024-09-30 09:34 UTC, azure-sdk commented
<!--chronus-github-change-commenter-->
All changed packages have been documented.
 - :white_check_mark: `@azure-tools/typespec-client-generator-core`

<details>
<summary>Show changes</summary>

### `@azure-tools/typespec-client-generator-core` - _feature_ [✏️](https://github.com/Azure/typespec-azure/edit/fix_enum_default_value/.chronus/changes/fix_enum_default_value-2024-8-30-17-30-54.md?pr=/Azure/typespec-azure/pull/1631)
> support value type for client default value
</details>

2024-09-30 09:53 UTC, azure-sdk commented
<!-- _TSP_TRYIT_COMMENT_ -->
You can try these changes here

| [🛝 Playground]( https://cadlplayground.z22.web.core.windows.net/typespec-azure/prs/1631/)|[🌐 Website](https://tspwebsitepr.z22.web.core.windows.net/typespec-azure/prs/1631/)|[📚 Next docs](https://tspwebsitepr.z22.web.core.windows.net/typespec-azure/prs/1631/docs/next.html) |
| ---|---|--- |

2024-09-30 09:53 UTC, haolingdong-msft commented on packages/typespec-client-generator-core/src/internal-utils.ts
> +      // TODO: handle scalar value
handle this TODO?

2024-10-07 15:19 UTC, iscai-msft requested changes
the `value` in tsp purposefully is meant to describe service default values, not client default values, so we shouldn't be having this support. There are a lot of issues with roundtrippability with default values, so we should only have `clientDefaultValue` in the specific cases of endpoint values and client api versions. Where is the push for this support coming from?

2024-10-08 02:22 UTC, tadelesh commented
> the `value` in tsp purposefully is meant to describe service default values, not client default values, so we shouldn't be having this support. There are a lot of issues with roundtrippability with default values, so we should only have `clientDefaultValue` in the specific cases of endpoint values and client api versions. Where is the push for this support coming from?

see the issue linked in description. there are cases that endpoint default value use value types, the support is only for those cases.

2024-10-08 13:35 UTC, iscai-msft commented
ah ok, sorry for the confusion, let me remove the blocking pr

2024-10-08 13:35 UTC, iscai-msft approved these changes

2024-10-08 14:34 UTC, merged