Fix linting rule action
Azure/typespec-azure pull request #1741
Opened 2024-10-24 16:48 UTC by AlitzelMendez

issue: https://github.com/Azure/typespec-azure/issues/1672

2024-10-24 16:51 UTC, azure-sdk commented
<!--chronus-github-change-commenter-->
All changed packages have been documented.
 - :white_check_mark: `@azure-tools/typespec-azure-resource-manager`

<details>
<summary>Show changes</summary>

### `@azure-tools/typespec-azure-resource-manager` - _fix_ [✏️](https://github.com/AlitzelMendez/typespec-azure/edit/fix-linting-rule-action/.chronus/changes/fix-linting-rule-action-2024-9-23-17-38-23.md?pr=/Azure/typespec-azure/pull/1741)
> Fix the `arm-resource-invalid-action-verb` rule. The rule should only allow `@post` and `@get` verbs, but it wasn't flagging other verbs.
</details>

2024-10-24 17:12 UTC, azure-sdk commented
<!-- _TSP_TRYIT_COMMENT_ -->
You can try these changes here

| [🛝 Playground]( https://cadlplayground.z22.web.core.windows.net/typespec-azure/prs/1741/)|[🌐 Website](https://tspwebsitepr.z22.web.core.windows.net/typespec-azure/prs/1741/)|[📚 Next docs](https://tspwebsitepr.z22.web.core.windows.net/typespec-azure/prs/1741/docs/next.html) |
| ---|---|--- |

2024-10-27 16:47 UTC, timotheeguerin approved these changes

2024-10-30 19:07 UTC, markcowl requested changes
One documentary change

2024-10-30 19:07 UTC, markcowl commented on docs/libraries/azure-resource-manager/rules/arm-resource-invalid-action-verb.md
> +@get op getAction is ArmProviderActionAsync<
```suggestion
@get op getAction is ArmProviderActionSync<
```

Asynchronous gets are not allowed

2024-10-31 17:43 UTC, markcowl approved these changes

2024-10-31 17:47 UTC, AlitzelMendez commented
PR Test: https://github.com/Azure/azure-rest-api-specs/actions/runs/11616708984/job/32350277825?pr=31352

2024-10-31 18:17 UTC, merged