Fix x-ms-identifiers rule to support inner properties
Azure/typespec-azure pull request #1744
Opened 2024-10-25 18:01 UTC by AlitzelMendez

issue: https://github.com/Azure/typespec-azure/issues/1742

2024-10-25 18:03 UTC, azure-sdk commented
<!--chronus-github-change-commenter-->
All changed packages have been documented.
 - :white_check_mark: `@azure-tools/typespec-azure-resource-manager`

<details>
<summary>Show changes</summary>

### `@azure-tools/typespec-azure-resource-manager` - _fix_ [✏️](https://github.com/AlitzelMendez/typespec-azure/edit/fix-x-ms-identifiers-rule/.chronus/changes/fix-x-ms-identifiers-rule-2024-9-25-10-44-57.md?pr=/Azure/typespec-azure/pull/1744)
> Fix the `x-ms-identifier` rule. The `x-ms-identifier` supports indexing into inner properties, but the linter does not support that and reports a warning.
</details>

2024-10-25 18:25 UTC, azure-sdk commented
<!-- _TSP_TRYIT_COMMENT_ -->
You can try these changes here

| [🛝 Playground]( https://cadlplayground.z22.web.core.windows.net/typespec-azure/prs/1744/)|[🌐 Website](https://tspwebsitepr.z22.web.core.windows.net/typespec-azure/prs/1744/)|[📚 Next docs](https://tspwebsitepr.z22.web.core.windows.net/typespec-azure/prs/1744/docs/next.html) |
| ---|---|--- |

2024-10-26 01:50 UTC, timotheeguerin commented on packages/typespec-azure-resource-manager/test/rules/missing-x-ms-identifiers.test.ts
> +          @OpenAPI.extension("x-ms-identifiers", ["food/brand/name"])
The doc linked in the issue mentioned that those should start with / in the example.

Not really sure if that's accurate but maybe we should support it or confirm there isn't use case of one or the other

2024-10-30 18:38 UTC, markcowl requested changes

2024-10-30 18:38 UTC, markcowl commented on packages/typespec-azure-resource-manager/test/rules/missing-x-ms-identifiers.test.ts
> +          @OpenAPI.extension("x-ms-identifiers", ["food/brand/name"])
I think we should also test an identifier that starts with `/` (i.e. /food/brand/name)

2024-10-31 18:17 UTC, merged