no-empty-model rule shouldn't warn on record models
Azure/typespec-azure pull request #1866
Opened 2024-11-14 17:42 UTC by AlitzelMendez

issue: https://github.com/Azure/typespec-azure/issues/1710

2024-11-14 17:44 UTC, azure-sdk commented
<!--chronus-github-change-commenter-->
All changed packages have been documented.
 - :white_check_mark: `@azure-tools/typespec-azure-resource-manager`

<details>
<summary>Show changes</summary>

### `@azure-tools/typespec-azure-resource-manager` - _fix_ [✏️](https://github.com/AlitzelMendez/typespec-azure/edit/fix-no-empty-model-rule/.chronus/changes/fix-no-empty-model-rule-2024-10-8-16-19-25.md?pr=/Azure/typespec-azure/pull/1866)
> Fix the `no-empty-model` rule to prevent it from being triggered for Records, as this is already covered by another rule.
</details>

2024-11-14 17:54 UTC, azure-sdk commented
<!-- _TSP_TRYIT_COMMENT_ -->
You can try these changes here

| [🛝 Playground]( https://cadlplayground.z22.web.core.windows.net/typespec-azure/prs/1866/)|[🌐 Website](https://tspwebsitepr.z22.web.core.windows.net/typespec-azure/prs/1866/)|[📚 Next docs](https://tspwebsitepr.z22.web.core.windows.net/typespec-azure/prs/1866/docs/next.html) |
| ---|---|--- |

2024-11-14 19:59 UTC, markcowl requested changes

2024-11-14 19:59 UTC, markcowl commented on packages/typespec-azure-resource-manager/src/rules/no-empty-model.ts
> +        if (model.properties.size === 0 && model.sourceModel?.name !== "Record") {
We should use the built-in compiler call for `isRecordModelType` as in this example: https://github.com/Azure/typespec-azure/blob/60f9e0682a8b3ff7e03fde33a2a199053db7d1d7/packages/typespec-autorest/src/openapi.ts#L1903

see import here: https://github.com/Azure/typespec-azure/blob/60f9e0682a8b3ff7e03fde33a2a199053db7d1d7/packages/typespec-autorest/src/openapi.ts#L87

2024-11-18 23:45 UTC, AlitzelMendez commented
validation result: https://github.com/Azure/azure-rest-api-specs/actions/runs/11902850879

2024-11-21 21:41 UTC, markcowl approved these changes

2024-11-22 17:57 UTC, merged