[WIP] x-ms-identifiers alternatives
Azure/typespec-azure pull request #1983
Opened 2024-12-12 22:20 UTC by AlitzelMendez

issue: https://github.com/Azure/typespec-azure/issues/1473

2024-12-12 22:23 UTC, azure-sdk commented
<!--chronus-github-change-commenter-->
All changed packages have been documented.
 - :white_check_mark: `@azure-tools/typespec-autorest`
 - :white_check_mark: `@azure-tools/typespec-azure-resource-manager`

<details>
<summary>Show changes</summary>

### `@azure-tools/typespec-autorest` - _feature_ [✏️](https://github.com/AlitzelMendez/typespec-azure/edit/x-ms-identifiers-alternatives/.chronus/changes/x-ms-identifiers-alternatives-2024-11-12-14-15-30.md?pr=/Azure/typespec-azure/pull/1983)
> Use the @identifiers decorator to identify and utilize identifiers for x-ms-identifiers. Additionally, use the @key decorator to identify identifiers.
### `@azure-tools/typespec-azure-resource-manager` - _feature_ [✏️](https://github.com/AlitzelMendez/typespec-azure/edit/x-ms-identifiers-alternatives/.chronus/changes/x-ms-identifiers-alternatives-2024-11-12-14-15-30.md?pr=/Azure/typespec-azure/pull/1983)
> Use the @identifiers decorator to identify and utilize identifiers for x-ms-identifiers. Additionally, use the @key decorator to identify identifiers.
</details>

2024-12-12 22:33 UTC, azure-sdk commented
<!-- _TSP_TRYIT_COMMENT_ -->
You can try these changes here

| [🛝 Playground]( https://cadlplayground.z22.web.core.windows.net/typespec-azure/prs/1983/)|[🌐 Website](https://tspwebsitepr.z22.web.core.windows.net/typespec-azure/prs/1983/)|[📚 Next docs](https://tspwebsitepr.z22.web.core.windows.net/typespec-azure/prs/1983/docs/next.html) |
| ---|---|--- |

2024-12-17 23:49 UTC, markcowl requested changes
A few changes - there is a subtlety that 'name' and 'id' properties remove the need for x-ms-identifiers.

Also, should have an up-to-date PR showing the changes this creates in azure-rest-api-specs repos

2024-12-17 23:49 UTC, markcowl commented on packages/samples/test/output/azure/core/data-plane/api-path-parameter/@azure-tools/typespec-autorest/2022-08-31/openapi.json
> +            "id"
We do not need to write x-ms-identifiers if there is an "id" or "name" property

2024-12-17 23:49 UTC, markcowl commented on packages/typespec-azure-resource-manager/src/resource.ts
> +export const $identifiers: IdentifiersDecorator = (
Need documentation comments to describe the use of the decorator and parameters

2024-12-17 23:49 UTC, markcowl commented on packages/typespec-azure-resource-manager/src/lib.ts
> +          "The @identifiers decorator expects a parameter that is an array of strings or an empty array as a parameter.",
```suggestion
          "The @identifiers decorator expects a parameter that is an array of strings or an empty array.",
```

2024-12-17 23:49 UTC, markcowl commented on packages/typespec-azure-resource-manager/README.md
> +
See comments below - need jsdoc comment to generate this data

2024-12-17 23:49 UTC, markcowl commented on packages/typespec-autorest/test/openapi-output.test.ts
> +describe("typespec-azure: identifiers decorator", () => {
Should add a test to verify that no extension is created when the object type contains a 'name' or 'id' property.

2024-12-26 20:12 UTC, AlitzelMendez commented on packages/typespec-azure-resource-manager/src/resource.ts
> +export function getArmIdentifiers(program: Program, entity: ArrayModelType): string[] | undefined {
I added the documentation but I am having problem with getting it generated, I will check what is missing

2025-01-09 22:21 UTC, markcowl requested changes

2025-01-09 22:21 UTC, markcowl commented on packages/typespec-autorest/src/openapi.ts
> +      const armIdentifiers = getArmIdentifiers(program, typespecType);
Note that name and id are considered valid as identifiers, even if they are not marked with `@key`

2025-01-09 22:21 UTC, markcowl commented on packages/typespec-autorest/test/openapi-output.test.ts
> +          bread: string;
```suggestion
          breed: string;
```

2025-01-09 22:21 UTC, markcowl commented on packages/typespec-autorest/test/openapi-output.test.ts
> +          @identifiers(["dogs/bread"])
```suggestion
          @identifiers(["dogs/breed"])
```

2025-01-09 22:21 UTC, markcowl commented on packages/typespec-autorest/test/openapi-output.test.ts
> +    deepStrictEqual(oapi.definitions.PetList.properties.pets["x-ms-identifiers"], ["dogs/bread"]);
```suggestion
    deepStrictEqual(oapi.definitions.PetList.properties.pets["x-ms-identifiers"], ["dogs/breed"]);
```

2025-01-09 22:21 UTC, markcowl commented on packages/typespec-azure-resource-manager/test/resource.test.ts
> +describe("typespec-azure-resource-manager: identifiers decorator", () => {
We should have another test here, where an array of models with a 'name' or 'id' property do not thrown any diagnostic, as 'name' and 'id' are automatically used if no x-ms-identifiers directive is present.

2025-01-09 22:57 UTC, markcowl commented on packages/typespec-azure-resource-manager/test/resource.test.ts
> +describe("typespec-azure-resource-manager: identifiers decorator", () => {
On second thought, we have this test, so I think we are ok

2025-01-09 22:57 UTC, markcowl approved these changes
Approved with a few minor nits

2025-01-10 01:18 UTC, merged