fixing missing Retry-After in DeleteLroResponse
Azure/typespec-azure pull request #410
Opened 2024-03-12 22:34 UTC by allenjzhang

2024-03-12 22:35 UTC, timotheeguerin approved these changes

2024-03-12 22:35 UTC, azure-sdk commented
<!--chronus-github-change-commenter-->
:x: There is undocummented changes. Run `chronus add` to add a changeset or [click here](https://github.com/allenjzhang/typespec-azure/new/azhang_fixRetryAfter?filename=.chronus/changes/azhang_fixRetryAfter-2024-2-12-22-35-31.md&value=---%0A%23%20Change%20versionKind%20to%20one%20of%3A%20internal%2C%20fix%2C%20dependencies%2C%20feature%2C%20deprecation%2C%20breaking%0AchangeKind%3A%20fix%0Apackages%3A%0A%20%20-%20%22%40azure-tools%2Ftypespec-azure-resource-manager%22%0A---%0A%0Afixing%20missing%20Retry-After%20in%20DeleteLroResponse).

**The following packages have changes but are not documented.**
 - :x:`@azure-tools/typespec-azure-resource-manager`

2024-03-12 22:42 UTC, markcowl requested changes

2024-03-12 22:42 UTC, markcowl commented on packages/typespec-azure-resource-manager/lib/responses.tsp
> +  LroHeaders extends TypeSpec.Reflection.Model = Azure.Core.Foundations.RetryAfterHeader &
I don't think we want to change the order

2024-03-12 22:50 UTC, azure-sdk commented
<!-- _CADL_TRYIT_COMMENT_ -->
You can try these changes at https://cadlplayground.z22.web.core.windows.net/typespec-azure/prs/410/

Check the website changes at https://tspwebsitepr.z22.web.core.windows.net/typespec-azure/prs/410/

2024-03-14 18:41 UTC, markcowl approved these changes

2024-03-14 19:10 UTC, merged