Add TypeSpec Feed using autorest-canonical emitter
Azure/typespec-azure pull request #598
Opened 2024-04-04 20:33 UTC by dinwa-ms

2024-04-09 22:24 UTC, markcowl requested changes

2024-04-09 22:24 UTC, markcowl commented on eng/feeds/arm-canonical/tspconfig_stand_alone.yaml
> +emit:
do not need this

2024-04-09 22:24 UTC, markcowl commented on eng/feeds/azure-canonical-scaffolding.json
@timotheeguerin  This is limited to only a few teams for this Semester, and the idea was not to confuse general users with this.  Once this idea is proven, I think we would either replace the existing template or add this as an option in the standard feed.

2024-04-09 22:24 UTC, markcowl commented on eng/feeds/azure-canonical-scaffolding.json
> +  "azure-core": {
should only need your template

2024-04-09 22:24 UTC, markcowl commented on eng/feeds/azure-canonical-scaffolding.json
> +  "azure-arm": {
do not need this

2024-04-09 22:24 UTC, markcowl commented on eng/feeds/azure-canonical-scaffolding.json
> +  "azure-arm-canonical": {
this is the only one that is needed

2024-04-09 22:24 UTC, markcowl commented on eng/feeds/azure-canonical-scaffolding.json
> +  "azure-core_stand_alone": {
do not need this

2024-04-09 22:24 UTC, markcowl commented on eng/feeds/azure-canonical-scaffolding.json
> +  "azure-arm_stand_alone": {
don't need this

2024-04-11 17:12 UTC, dinwa-ms commented on eng/feeds/azure-canonical-scaffolding.json
> +  "azure-arm_stand_alone": {
removed

2024-04-11 17:12 UTC, dinwa-ms commented on eng/feeds/azure-canonical-scaffolding.json
> +  "azure-core_stand_alone": {
removed

2024-04-11 17:13 UTC, dinwa-ms commented on eng/feeds/azure-canonical-scaffolding.json
> +  "azure-arm": {
removed

2024-04-11 17:13 UTC, dinwa-ms commented on eng/feeds/azure-canonical-scaffolding.json
> +  "azure-core": {
removed

2024-04-11 17:14 UTC, dinwa-ms commented on eng/feeds/arm-canonical/tspconfig_stand_alone.yaml
> +emit:
removed

2024-04-15 22:02 UTC, markcowl approved these changes

2024-04-15 23:19 UTC, allenjzhang commented on eng/feeds/azure-canonical-scaffolding.json
> +    "description": "Create a project with canonical swagger in rest-api-spec repo, representing an Azure service ARM API",
`Create standard ARM API project with an additional canonical swagger emitter in rest-api-spec repo`

2024-04-15 23:22 UTC, allenjzhang commented on eng/feeds/azure-canonical-scaffolding.json
> +    "description": "Create a project with canonical swagger in rest-api-spec repo, representing an Azure service ARM API",
Just noticed it is separate scaffolding json. Above not neccessary.

2024-04-15 23:44 UTC, merged