Adding a legacy Required properties resource mix models
Azure/typespec-azure pull request #833
Opened 2024-05-14 17:01 UTC by allenjzhang

Putting in a separate namespace avoid name conflict.

#131

2024-05-14 17:03 UTC, azure-sdk commented
<!--chronus-github-change-commenter-->
:x: There is undocummented changes. Run `chronus add` to add a changeset or [click here](https://github.com/allenjzhang/typespec-azure/new/azhang_addRequiredProperties?filename=.chronus/changes/azhang_addRequiredProperties-2024-4-14-17-3-52.md&value=---%0A%23%20Change%20versionKind%20to%20one%20of%3A%20internal%2C%20fix%2C%20dependencies%2C%20feature%2C%20deprecation%2C%20breaking%0AchangeKind%3A%20fix%0Apackages%3A%0A%20%20-%20%22%40azure-tools%2Ftypespec-azure-resource-manager%22%0A---%0A%0AAdding%20a%20legacy%20Required%20properties%20resource%20mix%20models).

**The following packages have changes but are not documented.**
 - :x:`@azure-tools/typespec-azure-resource-manager`

<details>
<summary>Show changes</summary>


</details>

2024-05-20 19:09 UTC, timotheeguerin commented on packages/typespec-azure-resource-manager/lib/legacy/models.tsp
> +//#region Standard Resource Operation Interfaces
do we supprot region in tsp?

2024-05-21 18:18 UTC, markcowl requested changes

2024-05-21 18:18 UTC, markcowl commented on packages/typespec-azure-resource-manager/lib/legacy/models.tsp
> +@doc("Concrete tracked resource types can be created by aliasing this type using a specific property type.")
I think these changes should be made to the standard templates, and the older ones should be marked as Legacy and deprecated.

2024-05-28 22:12 UTC, markcowl requested changes
I think we should consider a different approach, since this leaves out many important brownfield scenarios.  Also, a couple of inline nits

2024-05-28 22:12 UTC, markcowl commented on packages/typespec-azure-resource-manager/lib/legacy/models.tsp
> +using TypeSpec.Http;
For legacy, I think we are still leaving out scenarios where folks extend Resource or EntityResource.  I would prefer it if we just let them extend a common-types resource type, and added a new decorator they would need to decorate the type with that is the equivalent of `@armResourceInternal` and `@includeInapplicableMetadataInPayload`, and relax the rules around extension to include this case.

2024-05-28 22:12 UTC, markcowl commented on packages/typespec-azure-resource-manager/lib/legacy/models.tsp
> +//#region Standard Resource Operation Interfaces
remove

2024-05-28 22:12 UTC, markcowl commented on packages/typespec-azure-resource-manager/lib/models.tsp
> +  @doc("The resource-specific optional properties for this resource.")
I don't think these doc updates are necessary.  The typespec and the swagger already say it is optional, adding the documentation makes swagger changes without adding any information.

2024-06-03 17:09 UTC, allenjzhang commented on packages/typespec-azure-resource-manager/lib/legacy/models.tsp
> +model TrackedResourceWithRequiredProperties<Properties extends {}>
I feel the namespace being legacy which has good separation. It is targeted for brownfield. Unless ARM has disallowed required properties (currently they don't) we probably don't want to put deprecate.

2024-06-03 17:38 UTC, allenjzhang commented
This PR is ON HOLD until the discussion of @visibility design issues..

2024-07-09 19:26 UTC, closed without merging